// src/lib/pdfGenerator.ts
import jsPDF from "jspdf";
import { Student } from "@/types/student";

export interface FeePDFInfo {
  receipt_no?: string;
  month: string;
  year: number | string;
  registration_fee: number;
  monthly_fee: number;
  late_fee: number;
  stationary_charges: number;
  previous_balance: number;
  discount: number;
  total_amount: number;
  paid_amount?: number;
  remaining_amount?: number;
  payment_method?: string;
  status: "Paid" | "Unpaid" | string;
  issue_date?: string;
  due_date?: string;
}

/**
 * Generates a fee receipt/voucher PDF and triggers a download in the browser.
 */
export const generateFeePDF = (student: Student, receiptInfo: FeePDFInfo) => {
  const doc = new jsPDF();
  const isPaid = String(receiptInfo.status).toLowerCase() === "paid";
  const title = isPaid ? "PAYMENT RECEIPT" : "FEE VOUCHER";

  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 0, 128);
  doc.text(title, 105, 20, { align: "center" });

  // Student details
  doc.setFontSize(12);
  doc.text(`Student ID: ${student.student_id}`, 20, 40);
  doc.text(`Name: ${student.student_name}`, 20, 48);
  doc.text(`Class: ${student.class}`, 20, 56);

  // Receipt details
  doc.text(`Receipt No: ${receiptInfo.receipt_no ?? "N/A"}`, 20, 70);
  doc.text(`Month: ${receiptInfo.month} ${receiptInfo.year}`, 20, 78);
  doc.text(`Status: ${receiptInfo.status}`, 20, 86);

  // Amount items
  const items = [
    { label: "Registration Fee", value: receiptInfo.registration_fee },
    { label: "Monthly Fee", value: receiptInfo.monthly_fee },
    { label: "Late Fee", value: receiptInfo.late_fee },
    { label: "Stationary Charges", value: receiptInfo.stationary_charges },
    { label: "Previous Balance", value: receiptInfo.previous_balance },
    { label: "Discount", value: -receiptInfo.discount },
    { label: "Total Amount", value: receiptInfo.total_amount },
  ];

  let y = 100;
  doc.setFontSize(11);
  items.forEach(item => {
    const val = Math.abs(item.value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    doc.text(`${item.label}: PKR ${val}`, 20, y);
    y += 8;
  });

  if (isPaid) {
    doc.text(`Paid Amount: PKR ${receiptInfo.paid_amount?.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}`, 20, y);
    y += 8;
    doc.text(`Remaining Amount: PKR ${receiptInfo.remaining_amount?.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}`, 20, y);
    y += 8;
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by JSI Fee Management System", 105, 290, { align: "center" });

  const fileName = `${title.replace(/\s+/g, "_")}-${receiptInfo.receipt_no || "voucher"}.pdf`;
  doc.save(fileName);
};
