-- Alter the id column to ensure it is generated by default as identity.
-- This is necessary if the table was not created with the 'generated by default as identity' clause.
ALTER TABLE public.other_receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
